<?php 
//xcb_visual_class_t {
define('XCB_VISUAL_CLASS_STATIC_GRAY', 0);
define('XCB_VISUAL_CLASS_GRAY_SCALE', 1);
define('XCB_VISUAL_CLASS_STATIC_COLOR', 2);
define('XCB_VISUAL_CLASS_PSEUDO_COLOR', 3);
define('XCB_VISUAL_CLASS_TRUE_COLOR', 4);
define('XCB_VISUAL_CLASS_DIRECT_COLOR', 5);
//xcb_event_mask_t {
define('XCB_EVENT_MASK_NO_EVENT', 0);
define('XCB_EVENT_MASK_KEY_PRESS', 1);
define('XCB_EVENT_MASK_KEY_RELEASE', 2);
define('XCB_EVENT_MASK_BUTTON_PRESS', 4);
define('XCB_EVENT_MASK_BUTTON_RELEASE', 8);
define('XCB_EVENT_MASK_ENTER_WINDOW', 16);
define('XCB_EVENT_MASK_LEAVE_WINDOW', 32);
define('XCB_EVENT_MASK_POINTER_MOTION', 64);
define('XCB_EVENT_MASK_POINTER_MOTION_HINT', 128);
define('XCB_EVENT_MASK_BUTTON_1_MOTION', 256);
define('XCB_EVENT_MASK_BUTTON_2_MOTION', 512);
define('XCB_EVENT_MASK_BUTTON_3_MOTION', 1024);
define('XCB_EVENT_MASK_BUTTON_4_MOTION', 2048);
define('XCB_EVENT_MASK_BUTTON_5_MOTION', 4096);
define('XCB_EVENT_MASK_BUTTON_MOTION', 8192);
define('XCB_EVENT_MASK_KEYMAP_STATE', 16384);
define('XCB_EVENT_MASK_EXPOSURE', 32768);
define('XCB_EVENT_MASK_VISIBILITY_CHANGE', 65536);
define('XCB_EVENT_MASK_STRUCTURE_NOTIFY', 131072);
define('XCB_EVENT_MASK_RESIZE_REDIRECT', 262144);
define('XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY', 524288);
define('XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT', 1048576);
define('XCB_EVENT_MASK_FOCUS_CHANGE', 2097152);
define('XCB_EVENT_MASK_PROPERTY_CHANGE', 4194304);
define('XCB_EVENT_MASK_COLOR_MAP_CHANGE', 8388608);
define('XCB_EVENT_MASK_OWNER_GRAB_BUTTON', 16777216);
//xcb_backing_store_t {
define('XCB_BACKING_STORE_NOT_USEFUL', 0);
define('XCB_BACKING_STORE_WHEN_MAPPED', 1);
define('XCB_BACKING_STORE_ALWAYS', 2);
//xcb_image_order_t {
define('XCB_IMAGE_ORDER_LSB_FIRST', 0);
define('XCB_IMAGE_ORDER_MSB_FIRST', 1);
//xcb_mod_mask_t {
define('XCB_MOD_MASK_SHIFT', 1);
define('XCB_MOD_MASK_LOCK', 2);
define('XCB_MOD_MASK_CONTROL', 4);
define('XCB_MOD_MASK_1', 8);
define('XCB_MOD_MASK_2', 16);
define('XCB_MOD_MASK_3', 32);
define('XCB_MOD_MASK_4', 64);
define('XCB_MOD_MASK_5', 128);
define('XCB_MOD_MASK_ANY', 32768);
//xcb_key_but_mask_t {
define('XCB_KEY_BUT_MASK_SHIFT', 1);
define('XCB_KEY_BUT_MASK_LOCK', 2);
define('XCB_KEY_BUT_MASK_CONTROL', 4);
define('XCB_KEY_BUT_MASK_MOD_1', 8);
define('XCB_KEY_BUT_MASK_MOD_2', 16);
define('XCB_KEY_BUT_MASK_MOD_3', 32);
define('XCB_KEY_BUT_MASK_MOD_4', 64);
define('XCB_KEY_BUT_MASK_MOD_5', 128);
define('XCB_KEY_BUT_MASK_BUTTON_1', 256);
define('XCB_KEY_BUT_MASK_BUTTON_2', 512);
define('XCB_KEY_BUT_MASK_BUTTON_3', 1024);
define('XCB_KEY_BUT_MASK_BUTTON_4', 2048);
define('XCB_KEY_BUT_MASK_BUTTON_5', 4096);
//xcb_window_enum_t {
define('XCB_WINDOW_NONE', 0);
//xcb_button_mask_t {
define('XCB_BUTTON_MASK_1', 256);
define('XCB_BUTTON_MASK_2', 512);
define('XCB_BUTTON_MASK_3', 1024);
define('XCB_BUTTON_MASK_4', 2048);
define('XCB_BUTTON_MASK_5', 4096);
define('XCB_BUTTON_MASK_ANY', 32768);
//xcb_motion_t {
define('XCB_MOTION_NORMAL', 0);
define('XCB_MOTION_HINT', 1);
//xcb_notify_detail_t {
define('XCB_NOTIFY_DETAIL_ANCESTOR', 0);
define('XCB_NOTIFY_DETAIL_VIRTUAL', 1);
define('XCB_NOTIFY_DETAIL_INFERIOR', 2);
define('XCB_NOTIFY_DETAIL_NONLINEAR', 3);
define('XCB_NOTIFY_DETAIL_NONLINEAR_VIRTUAL', 4);
define('XCB_NOTIFY_DETAIL_POINTER', 5);
define('XCB_NOTIFY_DETAIL_POINTER_ROOT', 6);
define('XCB_NOTIFY_DETAIL_NONE', 7);
//xcb_notify_mode_t {
define('XCB_NOTIFY_MODE_NORMAL', 0);
define('XCB_NOTIFY_MODE_GRAB', 1);
define('XCB_NOTIFY_MODE_UNGRAB', 2);
define('XCB_NOTIFY_MODE_WHILE_GRABBED', 3);
//xcb_visibility_t {
define('XCB_VISIBILITY_UNOBSCURED', 0);
define('XCB_VISIBILITY_PARTIALLY_OBSCURED', 1);
define('XCB_VISIBILITY_FULLY_OBSCURED', 2);
//xcb_place_t {
define('XCB_PLACE_ON_TOP', 0);
define('XCB_PLACE_ON_BOTTOM', 1);
//xcb_property_t {
define('XCB_PROPERTY_NEW_VALUE', 0);
define('XCB_PROPERTY_DELETE', 1);
//xcb_time_t {
define('XCB_TIME_CURRENT_TIME', 0);
//xcb_atom_enum_t {
define('XCB_ATOM_NONE', 0);
define('XCB_ATOM_ANY', 0);

//xcb_colormap_state_t {
define('XCB_COLORMAP_STATE_UNINSTALLED', 0);
define('XCB_COLORMAP_STATE_INSTALLED', 1);
//xcb_colormap_enum_t {
define('XCB_COLORMAP_NONE', 0);
//xcb_mapping_t {
define('XCB_MAPPING_MODIFIER', 0);
define('XCB_MAPPING_KEYBOARD', 1);
define('XCB_MAPPING_POINTER', 2);
//xcb_window_class_t {
define('XCB_WINDOW_CLASS_COPY_FROM_PARENT', 0);
define('XCB_WINDOW_CLASS_INPUT_OUTPUT', 1);
define('XCB_WINDOW_CLASS_INPUT_ONLY', 2);
//xcb_cw_t {
define('XCB_CW_BACK_PIXMAP', 1);
define('XCB_CW_BACK_PIXEL', 2);
define('XCB_CW_BORDER_PIXMAP', 4);
define('XCB_CW_BORDER_PIXEL', 8);
define('XCB_CW_BIT_GRAVITY', 16);
define('XCB_CW_WIN_GRAVITY', 32);
define('XCB_CW_BACKING_STORE', 64);
define('XCB_CW_BACKING_PLANES', 128);
define('XCB_CW_BACKING_PIXEL', 256);
define('XCB_CW_OVERRIDE_REDIRECT', 512);
define('XCB_CW_SAVE_UNDER', 1024);
define('XCB_CW_EVENT_MASK', 2048);
define('XCB_CW_DONT_PROPAGATE', 4096);
define('XCB_CW_COLORMAP', 8192);
define('XCB_CW_CURSOR', 16384);
//xcb_back_pixmap_t {
define('XCB_BACK_PIXMAP_NONE', 0);
define('XCB_BACK_PIXMAP_PARENT_RELATIVE', 1);
//xcb_gravity_t {
define('XCB_GRAVITY_BIT_FORGET', 0);
define('XCB_GRAVITY_WIN_UNMAP', 0);
define('XCB_GRAVITY_NORTH_WEST', 1);
define('XCB_GRAVITY_NORTH', 2);
define('XCB_GRAVITY_NORTH_EAST', 3);
define('XCB_GRAVITY_WEST', 4);
define('XCB_GRAVITY_CENTER', 5);
define('XCB_GRAVITY_EAST', 6);
define('XCB_GRAVITY_SOUTH_WEST', 7);
define('XCB_GRAVITY_SOUTH', 8);
define('XCB_GRAVITY_SOUTH_EAST', 9);
define('XCB_GRAVITY_STATIC', 10);
//xcb_map_state_t {
define('XCB_MAP_STATE_UNMAPPED', 0);
define('XCB_MAP_STATE_UNVIEWABLE', 1);
define('XCB_MAP_STATE_VIEWABLE', 2);
//xcb_set_mode_t {
define('XCB_SET_MODE_INSERT', 0);
define('XCB_SET_MODE_DELETE', 1);
//xcb_config_window_t {
define('XCB_CONFIG_WINDOW_X', 1);
define('XCB_CONFIG_WINDOW_Y', 2);
define('XCB_CONFIG_WINDOW_WIDTH', 4);
define('XCB_CONFIG_WINDOW_HEIGHT', 8);
define('XCB_CONFIG_WINDOW_BORDER_WIDTH', 16);
define('XCB_CONFIG_WINDOW_SIBLING', 32);
define('XCB_CONFIG_WINDOW_STACK_MODE', 64);
//xcb_stack_mode_t {
define('XCB_STACK_MODE_ABOVE', 0);
define('XCB_STACK_MODE_BELOW', 1);
define('XCB_STACK_MODE_TOP_IF', 2);
define('XCB_STACK_MODE_BOTTOM_IF', 3);
define('XCB_STACK_MODE_OPPOSITE', 4);
//xcb_circulate_t {
define('XCB_CIRCULATE_RAISE_LOWEST', 0);
define('XCB_CIRCULATE_LOWER_HIGHEST', 1);
//xcb_prop_mode_t {
define('XCB_PROP_MODE_REPLACE', 0);
define('XCB_PROP_MODE_PREPEND', 1);
define('XCB_PROP_MODE_APPEND', 2);
//xcb_get_property_type_t {
define('XCB_GET_PROPERTY_TYPE_ANY', 0);
//xcb_send_event_dest_t {
define('XCB_SEND_EVENT_DEST_POINTER_WINDOW', 0);
define('XCB_SEND_EVENT_DEST_ITEM_FOCUS', 1);
//xcb_grab_mode_t {
define('XCB_GRAB_MODE_SYNC', 0);
define('XCB_GRAB_MODE_ASYNC', 1);
//xcb_grab_status_t {
define('XCB_GRAB_STATUS_SUCCESS', 0);
define('XCB_GRAB_STATUS_ALREADY_GRABBED', 1);
define('XCB_GRAB_STATUS_INVALID_TIME', 2);
define('XCB_GRAB_STATUS_NOT_VIEWABLE', 3);
define('XCB_GRAB_STATUS_FROZEN', 4);
//xcb_cursor_enum_t {
define('XCB_CURSOR_NONE', 0);
//xcb_button_index_t {
define('XCB_BUTTON_INDEX_ANY', 0);
define('XCB_BUTTON_INDEX_1', 1);
define('XCB_BUTTON_INDEX_2', 2);
define('XCB_BUTTON_INDEX_3', 3);
define('XCB_BUTTON_INDEX_4', 4);
define('XCB_BUTTON_INDEX_5', 5);
//xcb_grab_t {
define('XCB_GRAB_ANY', 0);
//xcb_allow_t {
define('XCB_ALLOW_ASYNC_POINTER', 0);
define('XCB_ALLOW_SYNC_POINTER', 1);
define('XCB_ALLOW_REPLAY_POINTER', 2);
define('XCB_ALLOW_ASYNC_KEYBOARD', 3);
define('XCB_ALLOW_SYNC_KEYBOARD', 4);
define('XCB_ALLOW_REPLAY_KEYBOARD', 5);
define('XCB_ALLOW_ASYNC_BOTH', 6);
define('XCB_ALLOW_SYNC_BOTH', 7);
//xcb_input_focus_t {
define('XCB_INPUT_FOCUS_NONE', 0);
define('XCB_INPUT_FOCUS_POINTER_ROOT', 1);
define('XCB_INPUT_FOCUS_PARENT', 2);
define('XCB_INPUT_FOCUS_FOLLOW_KEYBOARD', 3);
//xcb_font_draw_t {
define('XCB_FONT_DRAW_LEFT_TO_RIGHT', 0);
define('XCB_FONT_DRAW_RIGHT_TO_LEFT', 1);
//xcb_gc_t {
define('XCB_GC_FUNCTION', 1);
define('XCB_GC_PLANE_MASK', 2);
define('XCB_GC_FOREGROUND', 4);
define('XCB_GC_BACKGROUND', 8);
define('XCB_GC_LINE_WIDTH', 16);
define('XCB_GC_LINE_STYLE', 32);
define('XCB_GC_CAP_STYLE', 64);
define('XCB_GC_JOIN_STYLE', 128);
define('XCB_GC_FILL_STYLE', 256);
define('XCB_GC_FILL_RULE', 512);
define('XCB_GC_TILE', 1024);
define('XCB_GC_STIPPLE', 2048);
define('XCB_GC_TILE_STIPPLE_ORIGIN_X', 4096);
define('XCB_GC_TILE_STIPPLE_ORIGIN_Y', 8192);
define('XCB_GC_FONT', 16384);
define('XCB_GC_SUBWINDOW_MODE', 32768);
define('XCB_GC_GRAPHICS_EXPOSURES', 65536);
define('XCB_GC_CLIP_ORIGIN_X', 131072);
define('XCB_GC_CLIP_ORIGIN_Y', 262144);
define('XCB_GC_CLIP_MASK', 524288);
define('XCB_GC_DASH_OFFSET', 1048576);
define('XCB_GC_DASH_LIST', 2097152);
define('XCB_GC_ARC_MODE', 4194304);
//xcb_gx_t {
define('XCB_GX_CLEAR', 0);
define('XCB_GX_AND', 1);
define('XCB_GX_AND_REVERSE', 2);
define('XCB_GX_COPY', 3);
define('XCB_GX_AND_INVERTED', 4);
define('XCB_GX_NOOP', 5);
define('XCB_GX_XOR', 6);
define('XCB_GX_OR', 7);
define('XCB_GX_NOR', 8);
define('XCB_GX_EQUIV', 9);
define('XCB_GX_INVERT', 10);
define('XCB_GX_OR_REVERSE', 11);
define('XCB_GX_COPY_INVERTED', 12);
define('XCB_GX_OR_INVERTED', 13);
define('XCB_GX_NAND', 14);
define('XCB_GX_SET', 15);
//xcb_line_style_t {
define('XCB_LINE_STYLE_SOLID', 0);
define('XCB_LINE_STYLE_ON_OFF_DASH', 1);
define('XCB_LINE_STYLE_DOUBLE_DASH', 2);
//xcb_cap_style_t {
define('XCB_CAP_STYLE_NOT_LAST', 0);
define('XCB_CAP_STYLE_BUTT', 1);
define('XCB_CAP_STYLE_ROUND', 2);
define('XCB_CAP_STYLE_PROJECTING', 3);
//xcb_join_style_t {
define('XCB_JOIN_STYLE_MITER', 0);
define('XCB_JOIN_STYLE_ROUND', 1);
define('XCB_JOIN_STYLE_BEVEL', 2);
//xcb_fill_style_t {
define('XCB_FILL_STYLE_SOLID', 0);
define('XCB_FILL_STYLE_TILED', 1);
define('XCB_FILL_STYLE_STIPPLED', 2);
define('XCB_FILL_STYLE_OPAQUE_STIPPLED', 3);
//xcb_fill_rule_t {
define('XCB_FILL_RULE_EVEN_ODD', 0);
define('XCB_FILL_RULE_WINDING', 1);
//xcb_subwindow_mode_t {
define('XCB_SUBWINDOW_MODE_CLIP_BY_CHILDREN', 0);
define('XCB_SUBWINDOW_MODE_INCLUDE_INFERIORS', 1);
//xcb_arc_mode_t {
define('XCB_ARC_MODE_CHORD', 0);
define('XCB_ARC_MODE_PIE_SLICE', 1);
//xcb_clip_ordering_t {
define('XCB_CLIP_ORDERING_UNSORTED', 0);
define('XCB_CLIP_ORDERING_Y_SORTED', 1);
define('XCB_CLIP_ORDERING_YX_SORTED', 2);
define('XCB_CLIP_ORDERING_YX_BANDED', 3);
//xcb_coord_mode_t {
define('XCB_COORD_MODE_ORIGIN', 0);
define('XCB_COORD_MODE_PREVIOUS', 1);
//xcb_poly_shape_t {
define('XCB_POLY_SHAPE_COMPLEX', 0);
define('XCB_POLY_SHAPE_NONCONVEX', 1);
define('XCB_POLY_SHAPE_CONVEX', 2);
//xcb_image_format_t {
define('XCB_IMAGE_FORMAT_XY_BITMAP', 0);
define('XCB_IMAGE_FORMAT_XY_PIXMAP', 1);
define('XCB_IMAGE_FORMAT_Z_PIXMAP', 2);
//xcb_colormap_alloc_t {
define('XCB_COLORMAP_ALLOC_NONE', 0);
define('XCB_COLORMAP_ALLOC_ALL', 1);
//xcb_color_flag_t {
define('XCB_COLOR_FLAG_RED', 1);
define('XCB_COLOR_FLAG_GREEN', 2);
define('XCB_COLOR_FLAG_BLUE', 4);
//xcb_pixmap_enum_t {
define('XCB_PIXMAP_NONE', 0);
//xcb_font_enum_t {
define('XCB_FONT_NONE', 0);
//xcb_query_shape_of_t {
define('XCB_QUERY_SHAPE_OF_LARGEST_CURSOR', 0);
define('XCB_QUERY_SHAPE_OF_FASTEST_TILE', 1);
define('XCB_QUERY_SHAPE_OF_FASTEST_STIPPLE', 2);
//xcb_kb_t {
define('XCB_KB_KEY_CLICK_PERCENT', 1);
define('XCB_KB_BELL_PERCENT', 2);
define('XCB_KB_BELL_PITCH', 4);
define('XCB_KB_BELL_DURATION', 8);
define('XCB_KB_LED', 16);
define('XCB_KB_LED_MODE', 32);
define('XCB_KB_KEY', 64);
define('XCB_KB_AUTO_REPEAT_MODE', 128);
//xcb_led_mode_t {
define('XCB_LED_MODE_OFF', 0);
define('XCB_LED_MODE_ON', 1);
//xcb_auto_repeat_mode_t {
define('XCB_AUTO_REPEAT_MODE_OFF', 0);
define('XCB_AUTO_REPEAT_MODE_ON', 1);
define('XCB_AUTO_REPEAT_MODE_DEFAULT', 2);
//xcb_blanking_t {
define('XCB_BLANKING_NOT_PREFERRED', 0);
define('XCB_BLANKING_PREFERRED', 1);
define('XCB_BLANKING_DEFAULT', 2);
//xcb_exposures_t {
define('XCB_EXPOSURES_NOT_ALLOWED', 0);
define('XCB_EXPOSURES_ALLOWED', 1);
define('XCB_EXPOSURES_DEFAULT', 2);
//xcb_host_mode_t {
define('XCB_HOST_MODE_INSERT', 0);
define('XCB_HOST_MODE_DELETE', 1);
//xcb_family_t {
define('XCB_FAMILY_INTERNET', 0);
define('XCB_FAMILY_DECNET', 1);
define('XCB_FAMILY_CHAOS', 2);
define('XCB_FAMILY_SERVER_INTERPRETED', 5);
define('XCB_FAMILY_INTERNET_6', 6);
//xcb_access_control_t {
define('XCB_ACCESS_CONTROL_DISABLE', 0);
define('XCB_ACCESS_CONTROL_ENABLE', 1);
//xcb_close_down_t {
define('XCB_CLOSE_DOWN_DESTROY_ALL', 0);
define('XCB_CLOSE_DOWN_RETAIN_PERMANENT', 1);
define('XCB_CLOSE_DOWN_RETAIN_TEMPORARY', 2);
//xcb_kill_t {
define('XCB_KILL_ALL_TEMPORARY', 0);
//xcb_screen_saver_t {
define('XCB_SCREEN_SAVER_RESET', 0);
define('XCB_SCREEN_SAVER_ACTIVE', 1);
//xcb_mapping_status_t {
define('XCB_MAPPING_STATUS_SUCCESS', 0);
define('XCB_MAPPING_STATUS_BUSY', 1);
define('XCB_MAPPING_STATUS_FAILURE', 2);
//xcb_map_index_t {
define('XCB_MAP_INDEX_SHIFT', 0);
define('XCB_MAP_INDEX_LOCK', 1);
define('XCB_MAP_INDEX_CONTROL', 2);
define('XCB_MAP_INDEX_1', 3);
define('XCB_MAP_INDEX_2', 4);
define('XCB_MAP_INDEX_3', 5);
define('XCB_MAP_INDEX_4', 6);
define('XCB_MAP_INDEX_5', 7);
?>